examples/run.cmd
Runs from anywhere but mounts the location of the cmd file as the volume \ksml. based on the bash script in run.sh
=> Simple Windows command file to run KSMLRunner

.travis.yml, Makefile, ksml/src/main/java/io/axual/ksml/dsl/GlobalTableDefinition.java, ksml/src/main/java/io/axual/ksml/dsl/StreamDefinition.java, ksml/src/main/java/io/axual/ksml/dsl/TableDefinition.java, ksml/src/main/java/io/axual/ksml/parser/TopologyParseContext.java, ksml/src/test/java/io/axual/ksml/dsl/GlobalTableDefinitionTest.java, ksml/src/test/java/io/axual/ksml/dsl/StreamDefinitionTest.java, ksml/src/test/java/io/axual/ksml/dsl/TableDefinitionTest.java
Fix the failing unit tests, bring back names in topology
=> Fix unit tests

examples/ksml-runner.yml, ksml/src/main/java/io/axual/ksml/KSMLConfig.java, ksml/src/main/java/io/axual/ksml/KSMLTopologyGenerator.java, ksml/src/main/java/io/axual/ksml/generator/TopologyGeneratorImpl.java, ksml/src/main/java/io/axual/ksml/operation/package-info.java, ksml/src/main/java/io/axual/ksml/parser/TopologyParseContext.java, ksml/src/main/java/io/axual/ksml/parser/package-info.java, ksml/src/main/java/io/axual/ksml/python/Invoker.java, ksml/src/main/java/io/axual/ksml/python/package-info.java, ksml/src/main/java/io/axual/ksml/stream/package-info.java, ksml/src/main/java/io/axual/ksml/type/package-info.java, ksml/src/main/java/io/axual/ksml/user/UserFunction.java, ksml/src/main/java/io/axual/ksml/user/package-info.java, pom.xml
- added some package-info files and javadoc comments
- added javadoc plugin, generate docs with mvn javadoc:javadoc
(eventually we could generate and distribute a javadoc jar)
- added version to compiler plugin as IDE was complaining
=> Add javadoc

.gitignore, README.md, docker-compose.yml, docs/release-notes.md, examples/8-demo-count.yaml, ksml/src/main/java/io/axual/ksml/parser/TypeParser.java
=> Introduce graalvm

Dockerfile-build-runner
Bump Maven version in the multistage Dockerfile
=> bump Maven version

ksml-example-producer/pom.xml, ksml-query/src/main/java/io/axual/ksml/rest/server/GlobalState.java, ksml-query/src/main/java/io/axual/ksml/rest/server/RestServer.java, ksml-query/src/main/java/io/axual/ksml/rest/server/StoreResource.java
Codiga flagged the singleton implementation in `GlobalState` as not thread safe; replaced with an implementation using Java enum. Reran the build to verify still working.
I don't really understand why the logback commit is in here, as that change was already merged.
=> Fix singleton implementation

ksml-axual/pom.xml, ksml-query/pom.xml, ksml-reporting/pom.xml, ksml-runner-axual/pom.xml, ksml-runner/pom.xml, ksml/pom.xml, pom.xml
Added module ksml-reporting where coverage data for the whole project is aggregated.
=> aggregate jacoco reports

.github/workflows/build-and-test.yml, Dockerfile-build-runner, pom.xml
Fixes issue #33 by downloading the Maven distribution from the archives instead of the main site (which always only has one version).
=> #33: fix maven download

Dockerfile-build-runner, docker-compose.yml, examples/run.sh
Fix #41 by adding the missing table in `kafka-setup` in compose, small delay in `run.sh`
=> Resolve #41 : add missing table

ksml/src/test/java/io/axual/ksml/KSMLTopologyGeneratorBasicTest.java
Fixes #45 : verified that multistage build works with this fix.
=> fix #45 by converting Windows line endings

.github/workflows/build-push-docker.yml
Turns out the conditional needs ${{ ... }} around it; branch 'main' replaces 'master'
=> fix conditional syntax, branch name

.github/workflows/release-push-docker.yml
Added workflow which builds Docker images when a new release is built. Images are tagged with the tag of the release.
=> Add release workflow

.github/workflows/build-push-docker.yml
build and push snapshot docker image after PR from a fork is merged
=> run docker push workflow in target context (after PR was merged)

docs/plantuml/backend-class.puml, docs/plantuml/runner-config-class.puml, docs/plantuml/topology-generation.puml, docs/plantuml/usertypes.puml, ksml-runner-axual/src/main/java/io/axual/ksml/runner/backend/axual/AxualBackend.java, ksml-runner/src/main/java/io/axual/ksml/runner/backend/kafka/KafkaBackend.java, ksml/src/main/java/io/axual/ksml/KSMLTopologyGenerator.java, ksml/src/main/java/io/axual/ksml/data/mapper/NativeUserObjectMapper.java, ksml/src/test/java/io/axual/ksml/parser/UserTypeParserTest.java
This PR adds some internal diagrams and one extra unit test
=> Add internal doc, unit test

Dockerfile
Update the docker base image to UBI 8.6-990
Fix for issue #58
=> Update dockerfile to use newer UBI base image

ksml-axual/pom.xml, ksml-query/pom.xml, ksml-runner-axual/pom.xml, ksml-runner/pom.xml, ksml/pom.xml, ksml/src/test/java/io/axual/ksml/parser/UserTypeParserTest.java, pom.xml
- Updated Kafka dependencies to 3.2.3
- Updated Axual dependencies to 6.0.4
- Updated several other dependencies
- Resolved convergence errors
=> Update to kafka 3.2.3

ksml/src/main/java/io/axual/ksml/python/PythonFunction.java, ksml/src/test/java/io/axual/ksml/python/PythonFunctionTest.java
In Java 17 we have multiline strings, which IMHO could help with readability of PythonFunction.
I also added a unit test to verify that the class works.
=> use Java17 multiline string in PythonFunction, add unit test

.github/workflows/build-push-docker.yml, .github/workflows/release-push-docker.yml, Dockerfile, ksml-data-generator/pom.xml, pom.xml
- Refactored the Dockerfile to use caches for RUN statements per target architecture
- Updated POMs to use Maven Dependency Plugin 3.5.0. This enables a proper go-offline call with multi module projects
- Updated  docker/build-push-action to version 4
=> Optimized Docker build

Dockerfile
Added the explicit user Graal with uid 1024 allows gu and graalpy to work properly
Adding a new venv builder image that allows to install python packages
closing #72
=> Docker image, GraalPy venv, install and GU commands fail

ksml/src/main/java/io/axual/ksml/operation/JoinOperation.java, ksml/src/main/java/io/axual/ksml/operation/LeftJoinOperation.java, ksml/src/main/java/io/axual/ksml/operation/OuterJoinOperation.java
=> Fix stream-stream join validation and align other checks

ksml-kafka-clients/src/main/java/io/axual/ksml/client/admin/ResolvingAdmin.java
Updated the resolving admin client
- Added TopicPartition resolving to listConsumerGroupOffset specifications, this caused failures when using resolvers.
- Updated the resolving createTopic implementation to also copy the config map for the copy.
Tested on actual Axual platform.
Running Join test with Docker snapshot branch reproduced the issue
Running the same test with a locally build KSML does not have this issue any more
=> Fix resolving admin client issues causing warning messages

docker-compose.yml, examples/ksml-runner.yaml, ksml-data-avro/pom.xml, ksml-data-xml/src/main/java/io/axual/ksml/data/notation/xml/XmlDataObjectMapper.java, ksml-data-xml/src/main/java/io/axual/ksml/data/notation/xml/XmlSchemaMapper.java
Update dependent commons-compress version which fixes CVE-2024-25710 /  CVE-2024-26308
Prevent possible null pointer exception
Use secure XML processing
Not reported by scan. Add missing example topic to docker compose
=> Fix issues reported by Sonar and Trivy scans

.github/workflows/build-and-test.yml, ksml-runner/src/test/java/io/axual/ksml/runner/backend/KafkaProducerRunnerTest.java
Thia PR makes the "build and test" workflow use the same jobs as the "build and push docker" and "release and push docker" workflows, so possible errors can be detected at the moment the PR is made.
=> Unified build workflows

ksml-data-xml/NOTICE.txt, ksml-runner/src/main/java/io/axual/ksml/runner/backend/KafkaStreamsRunner.java, ksml/src/main/java/io/axual/ksml/TopologyGenerator.java
Fixes the issue that tables no longer have values after a restart, causing joins to fail.
This PR forwarding optimisation setting and enables optimisations by default
Closes issue #135
=> Fix issue Joins not working. No optimisation causes tables to have no data

ksml-data/src/main/java/io/axual/ksml/data/loader/SchemaLoader.java, ksml/src/main/java/io/axual/ksml/TopologyGenerator.java
Fix small log issue with TopologyGenerator using multiple log statements.
Closing #105
=> Make sure the file system specific separator character is used.

ksml/src/main/java/io/axual/ksml/python/PythonFunction.java, ksml/src/main/java/io/axual/ksml/user/UserFunction.java
The logs and exceptions thrown by functions was missing namespace information, making issue tracking harder.
Updated UserFunction and PythonFunction to log messages and create exceptions containing the Namespace and Name of the function.
=> Add namespace and name to Function log messages and exceptions

ksml-data/src/main/java/io/axual/ksml/data/mapper/NativeDataObjectMapper.java, ksml-data/src/main/java/io/axual/ksml/data/util/MapUtil.java, ksml/src/main/java/io/axual/ksml/python/PythonDataObjectMapper.java
* Fix NativeDataObjectMapper
* Fix PythonDataObjectMapper
=> Fix crash when using AVRO CharSequence encodings and nested objects

.github/dependabot.yaml
Daily dependency update checks for maven, docker and Github actions.
=> SEC-424 // Add dependabot.yaml with daily checks

ksml/src/test/java/io/axual/ksml/KSMLBranchingTest.java, ksml/src/test/java/io/axual/ksml/KSMLCopyTest.java, ksml/src/test/java/io/axual/ksml/KSMLFilterTest.java, ksml/src/test/java/io/axual/ksml/KSMLJoinTest.java, ksml/src/test/java/io/axual/ksml/KSMLReduceTest.java, ksml/src/test/java/io/axual/ksml/KSMLRoutingTest.java, ksml/src/test/java/io/axual/ksml/KSMLStateStoreTest.java, ksml/src/test/java/io/axual/ksml/python/PythonContextConfigTest.java, ksml/src/test/java/io/axual/ksml/python/PythonContextTest.java, ksml/src/test/java/io/axual/ksml/testutil/KSMLDriver.java, ksml/src/test/java/io/axual/ksml/testutil/KSMLTestExtension.java, ksml/src/test/java/io/axual/ksml/testutil/KSMLTopic.java, ksml/src/test/resources/pipelines/test-reduce.yaml
This PR adds a first operation test and also improves simplicity and readability of KSML stream tests. Linking a `TestInputTopic` in the code to a topic in the stream is now done on the field level; same for `TestOutputTopic` and optionally to the `TopologyTestDriver` if needed. Key and value type AVRO are still supported by the annotations.
All tests have been adjusted to the new way of writing.
For example nstead of writing a test like this:
```java
@ExtendWith(KSMLTestExtension.class)
public class KSMLRoutingTest {
TestInputTopic inputTopic;
TestOutputTopic outputSensor0;
TestOutputTopic outputSensor1;
TestOutputTopic outputSensor2;
@KSMLTest(topology = "pipelines/test-routing.yaml",
inputTopics = {@KSMLTopic(variable = "inputTopic", topic = "ksml_sensordata_avro")},
outputTopics = …
```
=> First KSML operation test, simplify test annotations

.run/KSML example processor LOCAL.run.xml, .run/KSML example producer LOCAL.run.xml, CONTRIBUTING.md, README.md, docs/runners.md, ksml-runner/src/main/java/io/axual/ksml/runner/prometheus/PrometheusExport.java, workspace/local/ksml-data-generator-local.yaml, workspace/local/ksml-runner-local.yaml
Rewrote README.md, CONTRIBUTING.md, runners.md with setup, testing, metrics, and contributions guidelines
Added these files for easy local setup:
- `ksml-data-generator-local.yaml`
- `ksml-runner-local.yaml`
=> Docs: rewrite CONTRIBUTING.md 

ksml/src/main/java/io/axual/ksml/TopologyGenerator.java, ksml/src/main/java/io/axual/ksml/definition/StateStoreDefinition.java, ksml/src/main/java/io/axual/ksml/definition/WindowStateStoreDefinition.java, ksml/src/main/java/io/axual/ksml/operation/BaseOperation.java, ksml/src/main/java/io/axual/ksml/operation/JoinWithStreamOperation.java, ksml/src/main/java/io/axual/ksml/operation/LeftJoinWithStreamOperation.java, ksml/src/main/java/io/axual/ksml/operation/OuterJoinWithStreamOperation.java
* Fix in WindowStateStoreDefinition that copied the wrong value into its windowSize
* Checks in BaseOperation to validate window store parameters with JoinWindows
* Update in TopologyGenerator to skip manual creation of join operation state stores
=> Improve the window handling of joins with streams

examples/00-example-dump-messages.yaml
* Adds timestamp and headers to the logged output
=> Extend dump definition with timestamp and headers

ksml/src/main/java/io/axual/ksml/parser/DurationParser.java, ksml/src/test/java/io/axual/ksml/parser/DurationParserTest.java
=> Added ms as a known duration unit
