Dockerfile

The new Dockerfile will use the Red Hat UBI image and download GraalVM 21.

Use GraalVM in Dockerfile

---

ksml-example-producer/pom.xml

Bump logback version because of Snyk warning

bump logback version

---

.github/workflows/build-and-test.yml
Dockerfile-build-runner
ksml-query/pom.xml
ksml-runner-axual/pom.xml
ksml-runner/pom.xml
ksml/pom.xml
pom.xml

- added jacoco plugin to Maven build
- run workflow on branches recognized as long lived by Sonarcloud (`branch-*`)
- need to add a workflow secret for SONAR_TOKEN
Verified on my fork that coverage is now shown in Sonarcloud.

Add coverage data, fix docker multistage

---

examples/ksml-runner.yml
ksml-runner-axual/src/main/java/io/axual/ksml/runner/backend/axual/AxualBackend.java
ksml-runner/pom.xml
ksml-runner/src/main/java/io/axual/ksml/runner/KSMLRunner.java
ksml-runner/src/main/java/io/axual/ksml/runner/backend/kafka/KafkaBackend.java
ksml-runner/src/main/java/io/axual/ksml/runner/config/KSMLConfig.java
ksml-runner/src/main/java/io/axual/ksml/runner/config/KSMLRunnerConfig.java
ksml-runner/src/test/java/io/axual/ksml/runner/config/KSMLConfigTest.java
ksml-runner/src/test/java/io/axual/ksml/runner/config/KsmlRunnerConfigTest.java
ksml-runner/src/test/resources/example-definition.yaml
ksml-runner/src/test/resources/ksml-config-no-configdir.yml
ksml-runner/src/test/resources/ksml-config-wrong-configdir.yml
ksml-runner/src/test/resources/ksml-config.yml
ksml-runner/src/test/resources/ksml-runner-config.yml
ksml/src/main/java/io/axual/ksml/KSMLConfig.java
ksml/src/main/java/io/axual/ksml/KSMLTopologyGenerator.java
ksml/src/main/java/io/axual/ksml/generator/TopologyGeneratorImpl.java

This PR resolves #36 by making it possible to have separate work and config directories, and adjusting `example/ksml-runner.yml` so that the working directory is inside the container. Tested on Ubuntu 20.04 and verified that the issue does not occur anymore when following the README.

resolve #36 by having workdirectory inside container

---

examples/ksml-runner.yml
ksml-axual/pom.xml
ksml-query/pom.xml
ksml/pom.xml
ksml/src/test/java/io/axual/ksml/KSMLTopologyGeneratorBasicTest.java
pom.xml

This PR fixes issues #37 (and duplicate #35) by upgrading the confluent.version to 7.1.1 which removes the transitive dependency. As a result apache.avro.version needed to be upgraded to 1.11.0 as well.
Rebuilt axual/ksml and verified that examples work (with the exception of `10-demo-queryabletable.yaml`??)

resolve #37 and #35 by upgrading dependencies

---

ksml/src/test/java/io/axual/ksml/KSMLTopologyGeneratorBasicTest.java

Currently, it's not possible to use Liberica NIK to compile and test because the `checkGraalVM()` method fails : 
```
org.opentest4j.AssertionFailedError: This test needs GraalVM to work, found java.vendor.url=https://bell-sw.com/
at io.axual.ksml.KSMLTopologyGeneratorBasicTest.checkGraalVM(KSMLTopologyGeneratorBasicTest.java:57)
```
As mentioned by Oleg Šelajev in this [StackOverflow thread](https://stackoverflow.com/questions/64902270/how-can-i-tell-in-a-standard-java-program-if-im-running-in-graalvm-or-not), a cleaner (and generic) way to check if we use GraalVM is to use the [`Version.isRelease()`](https://www.graalvm.org/sdk/javadoc/org/graalvm/home/Version.html) method from the `graal-sdk`.

Support Liberica NIK

---

.github/workflows/build-push-docker.yml
examples/ksml-runner.yml

This PR fixes #17 by building and pushing `:snapshot` versions of the runner image when a pull request merges.

Build snapshot Docker image on pull request merged

---

.github/workflows/build-and-test.yml
Dockerfile
Dockerfile-build-runner
pom.xml

Updated project to build for Java 17 (Latest LTS)
Updated dependencies, lombok required for Java17
Docker build files use Graal 22.1 Java 17 releases now
Local builds work with Liberica NIK 22.1-R17 release

Update to Java 17

---

examples/01-demo-inspect.yaml
examples/02-demo-copy.yaml
examples/03-demo-filter.yaml
examples/04-demo-branch.yaml
examples/05-demo-dynamicrouting.yaml
examples/06-demo-double.yaml
examples/07-demo-convert.yaml
examples/08-demo-count.yaml
examples/09-demo-aggregate.yaml
examples/10-demo-queryabletable.yaml

The examples dated back to Jython days when Python 3 syntax was not yet supported. Now that we do support it, we can simplify the print_message syntax.

Update the print statements in examples with Python 3 syntax

---

.github/workflows/build-and-test.yml

The following actions needed updates following warnings during workflow runs for Build and Test.
- actions/checkout v2 -> v3
- actions/setup-java v2 -> v3
- actions/cache v1 -> v3

Update GitHub Actions

---

Dockerfile

This PR provides a new Dockerfile to build the KSML Runner and KSML Data Generator images.
It fixes the problems by 
- Using a dedicated KSML user (id 1024) which owns the GraalVM/Python installation.
- Adding a fill GCC/G++ build stack to allow Python packages to be build
- Adding other required utilities such as tar, curl and gzip
- Download scripts have been optimized to download and extract in one step
The multistage build allows for very efficient target images .
Tested by 
- installing numpy as specified in the issue
- Running the KSML container against a real Kafka and topic
- Running the KSML Data Generator against a real Kafka and topic
Closes Axual/ksml#72

Issue #72 - Fix build failures when trying to use venv and install python packages

---

.github/workflows/build-and-test.yml
Dockerfile
examples/run.sh
graalpy-module-collection/pom.xml
graalpy-module-collection/src/main/java/module-info.java
ksml-data-generator/pom.xml
ksml-query/pom.xml
ksml-reporting/pom.xml
ksml-runner/pom.xml
ksml/pom.xml
pom.xml

Updated pom dependencies to Java 21
Added GraalVM Polyglot, GraalVM Python dependencies to pom.xml since they've been removed from GraalVM distribution.
Added new maven sub module to define and download GraalVM Polyglot, GraalVM Python and Truffle modules to make sure Java21 can find the modules.
Updated Docker build to:
- use GraalVM for JDK 21
- Copy the GraalVM, Python and Python modules to a separate directory
- Update the entrypoint to use the `upgrade-module-path` option when starting KSML and DataGen
Updated Github Actions to download and use GraalVM for JDK 21 Community
Tests run
- All unit/integration tests
- Local Docker BuildX build as described in the readme
- Run the example docker compose and run.sh using the local build images
- Manually tested the updated GitHub Action, …

Update to GraalVM for JDK 21 Community

---

ksml-runner/src/main/java/io/axual/ksml/runner/KSMLRunner.java

The exception handling of KSML stops the Kafka Streams and other flows, but the executor service is not shut down in this flow.
Moved the KSMLRunner executor service shutdown to the finally block to make sure it is always stopped

Fix KSML java process not stopping on exception

---

ksml-runner/src/main/java/io/axual/ksml/runner/backend/KafkaBackend.java
ksml/src/main/java/io/axual/ksml/KSMLTopologyGenerator.java
ksml/src/main/java/io/axual/ksml/TopologyGenerator.java
ksml/src/main/java/io/axual/ksml/generator/TopologyGeneratorImpl.java
ksml/src/main/java/io/axual/ksml/parser/topology/TopologyParseContext.java
ksml/src/test/java/io/axual/ksml/KSMLTopologyGeneratorBasicTest.java

Refactor to provide streams configuration to topology builder. This allows optimisation to take place, and reduces the need for table changelog topics along with other Kafka Streams optimisations

Fix to enable Streams optimisations to be applied to topology

---

ksml/src/test/java/io/axual/ksml/TopologyGeneratorBasicTest.java
ksml/src/test/resources/reference/1-reference.txt
ksml/src/test/resources/reference/2-reference.txt
ksml/src/test/resources/reference/3-reference.txt
ksml/src/test/resources/reference/4-reference.txt
ksml/src/test/resources/reference/5-reference.txt

During the refactoring the topology generator tests were partially disabled and never reactivated.
Updated the tests to match the current initialisation logic.
Updated the reference files to match the expected topology names

Enabled Topology Generator Basic test to verify topology and topology naming

---

ksml-runner/pom.xml
ksml-runner/src/main/java/io/axual/ksml/runner/logging/KSMLLogbackConfigurator.java
ksml-runner/src/main/resources/META-INF/services/ch.qos.logback.classic.spi.Configurator
ksml-runner/src/test/java/io/axual/ksml/runner/logging/KSMLLogbackConfiguratorTest.java
ksml-runner/src/test/java/io/axual/ksml/runner/logging/MockAppender.java
ksml-runner/src/test/resources/logback-custom-testing.xml
ksml-runner/src/test/resources/logback-test.xml
pom.xml

Implement Logback Configuration for KSML which can read a file location from the  environment variable, and loads it.
Precedence logic is
1. If system property `logback.configurationFile` is set, use the file referenced there
2. If the environment variable `LOGBACK_CONFIGURATION_FILE` is set, use the file referenced there
3. Fallback to the DefaultJoranConfiguration logic, looking for `logback-test.xml` and `logback.xml`
Tested with a local build with the provided docker compose, the custom logback configuration was loaded

Enable custom logback configuration support

---

.github/workflows/build-and-test.yml

If you fork the project the action in your forks fail because of missing Sonarcloud credentials.
This fix checks the repository name, and if it isn't _Axual/ksml_ it won't set the extra commands for a maven sonar scan

Update build to not run sonarscan on forks

---

ksml-runner/src/main/java/io/axual/ksml/runner/prometheus/PrometheusExport.java

The PrometheusExport can get a NullPointer Exception if a try with resources fails and the stop is called again.
The Optional ofNullable is used to determine if the collector unregister calls can be done.

Fix NullPointer exception in PrometheusExport

---

ksml-runner/src/main/java/io/axual/ksml/runner/KSMLRunner.java
ksml-runner/src/main/resources/ksml/ksml-info.properties
ksml-runner/src/test/resources/ksml/ksml-info.properties
pom.xml

The previous implementation to get the version and name of KSML used the manifest. This didn't work with the module load, the wrong manifest was loaded.
This new implementation uses a custom properties file and the Maven Resources Plugin

Use custom properties file to get version information

---

ksml-kafka-clients/pom.xml
ksml-kafka-clients/src/main/java/io/axual/ksml/client/resolving/GroupPatternResolver.java
ksml-kafka-clients/src/test/java/io/axual/ksml/client/resolving/GroupPatternResolverTest.java

Added an alias support for group id patterns. Axual deployments can use the pattern {group} as equivalent to {group.id}

Add group as alias for group.id in patterns

---

ksml-runner/pom.xml

Set dependency plugin to also download runtime dependencies. 
This allows the compression libraries to be available again

Add runtime dependencies to KSML image

---

ksml-query/src/main/java/io/axual/ksml/rest/server/ComponentState.java
ksml-query/src/main/java/io/axual/ksml/rest/server/GlobalState.java
ksml-query/src/main/java/io/axual/ksml/rest/server/KeyValueStoreResource.java
ksml-query/src/main/java/io/axual/ksml/rest/server/KsmlQuerier.java
ksml-query/src/main/java/io/axual/ksml/rest/server/ReadyResource.java
ksml-query/src/main/java/io/axual/ksml/rest/server/RestServer.java
ksml-query/src/main/java/io/axual/ksml/rest/server/RestServerExceptionMapper.java
ksml-query/src/main/java/io/axual/ksml/rest/server/StoreResource.java
ksml-query/src/main/java/io/axual/ksml/rest/server/WindowedKeyValueStoreResource.java
ksml-runner/src/main/java/io/axual/ksml/runner/KSMLRunner.java
ksml-runner/src/main/java/io/axual/ksml/runner/backend/IntervalSchedule.java
ksml-runner/src/main/java/io/axual/ksml/runner/backend/KafkaProducerRunner.java
ksml-runner/src/main/java/io/axual/ksml/runner/backend/KafkaStreamsRunner.java
packaging/helm-charts/ksml/templates/statefulset.yaml
packaging/helm-charts/ksml/values.schema.json
packaging/helm-charts/ksml/values.yaml

A Readiness service has been added to the KSML service, reachable on path `/ready`
The helm charts have been updated with default readiness, liveness and startup probes.
The KSML Runner has been updated to start the RestServer as soon as possible to provide the services.
The existing services has been updated to provide Service Unavailable (503) statuses during startup.
Queries to a non existent state store will result in a Not Found (404) status.
The RestServer now handles WebApplicationExceptions explicitly, returning the corresponding status codes
The StreamsQuerier interface has been renamed KsmlQuerier since it also supplies other information.
Removed the StoreQuerier class, as it was not used by any component.

Implement Readiness service and probes

---

packaging/helm-charts/ksml/.helmignore
packaging/helm-charts/ksml/README.md
packaging/helm-charts/ksml/templates/NOTES.txt
packaging/helm-charts/ksml/templates/service.yaml
packaging/helm-charts/ksml/templates/servicemonitor.yaml
packaging/helm-charts/ksml/templates/statefulset.yaml
packaging/helm-charts/ksml/values.yaml

This PR contains several changes to make sure ServiceMonitor and Prometheus export settings match:
- Update KSML ServiceMonitor to be disabled if Prometheus export is not configured.
- Added a warning in the nodes if ServiceMonitor is enabled, but Prometheus is not. 
- Statefulset and service will only define metrics port if Prometheus is enabled
- Update example in Helm Readme, it used the wrong filename in the definition

Fix logic issue with Prometheus Export and ServiceMonitor

---

ksml-runner/src/main/java/io/axual/ksml/runner/KSMLRunner.java
ksml-runner/src/main/java/io/axual/ksml/runner/backend/KafkaProducerRunner.java
ksml-runner/src/main/java/io/axual/ksml/runner/backend/KafkaStreamsRunner.java
ksml/src/main/java/io/axual/ksml/execution/FatalError.java

Excessive CPU usage was reported. Traced to the Runner implementations, which used a busy wait loop.
Update runners to throw exceptions and use CompletableFutures which can be joined and waited for.
Updated FatalError to use a StringBuilder to build a single error message instead of multiple log statements

Fix excessive CPU Usage

---

ksml-data/src/main/java/io/axual/ksml/data/mapper/NativeDataObjectMapper.java
ksml-data/src/main/java/io/axual/ksml/data/util/MapUtil.java
ksml/src/main/java/io/axual/ksml/python/PythonDataObjectMapper.java

* Fix NativeDataObjectMapper
* Fix PythonDataObjectMapper

[Backport] Fix crash when using AVRO CharSequence encodings and nested objects

---

Dockerfile
examples/ksml-runner.yaml
ksml-runner/src/main/java/io/axual/ksml/runner/config/KSMLConfig.java
ksml-runner/src/main/java/io/axual/ksml/runner/exception/ConfigException.java
packaging/helm-charts/ksml/templates/configmap-runner.yaml
packaging/helm-charts/ksml/templates/statefulset.yaml
packaging/helm-charts/ksml/values.schema.json
packaging/helm-charts/ksml/values.yaml

There were several issues related to the state storage.
The first was that the Kubernetes mounted volume did not match the ownership as the default user in the KSML image.
This was fixed by creating the KSML user with primary group 0 (root)
There is also a change that will allow KSML to create the storage directory if it does not exist.
A new  config parameter has been added to enable creation of the storage directory

Fix several storage issues and allow storageDIrectory creation

---

Dockerfile
ksml-runner/pom.xml
ksml-runner/src/test/java/io/axual/ksml/runner/backend/KafkaProducerRunnerTest.java
pom.xml

Docker build will skip tests if target and build architecture don't match.
Use awaitility to wait for message instead of a 60 second sleep

Fix slow and failing builds with multiple architectures (1.0.x)

---

packaging/helm-charts/ksml/README.md
packaging/helm-charts/ksml/templates/network-policy.yaml
packaging/helm-charts/ksml/values.yaml

Add optional NetworkPolicy resource that can be used to control `ingress` and `egress` rules applied to the KSML pod.
By default the NetworkPolicy will be disabled.

Add NetworkPolicy k8s-resource to KSML helm-charts

---

Dockerfile
ksml-runner/src/main/java/io/axual/ksml/runner/backend/KafkaStreamsRunner.java
ksml/src/main/java/io/axual/ksml/metric/KsmlMetricsReporter.java
ksml/src/main/java/io/axual/ksml/metric/KsmlTagEnricher.java
ksml/src/main/java/io/axual/ksml/metric/MetricTags.java
ksml/src/main/java/io/axual/ksml/metric/MetricsRegistry.java
ksml/src/test/java/io/axual/ksml/metric/KsmlMetricsReporterTest.java
ksml/src/test/java/io/axual/ksml/metric/KsmlTagEnricherTest.java

- Add KsmlMetricsReporter to convert Kafka Streams latency metrics into KSML-compliant metrics
- Implement KsmlTagEnricher to parse processor node names and extract namespace/pipeline/operation metadata
- Filter and enrich only e2e latency metrics (avg/min/max) from stream-processor-node-metrics group
- Add integration tests validating JMX bean registration and metric value updates
- Include pattern matching tests for various node naming conventions
The changes enable monitoring of KSML pipeline performance by enriching Kafka Streams metrics with contextual tags, making it easier to track latency across specific namespaces, pipelines and operations.

Implement Kafka Streams metrics reporter with KSML tag enrichment

---

examples/07-example-convert.yaml
examples/13-example-join.yaml
examples/sensor_data.proto
ksml-data-json/src/main/java/io/axual/ksml/data/notation/json/JsonDataObjectConverter.java
ksml-data-xml/src/main/java/io/axual/ksml/data/notation/xml/XmlDataObjectConverter.java
ksml-data-xml/src/main/java/io/axual/ksml/data/notation/xml/XmlNotation.java
ksml-data/src/main/java/io/axual/ksml/data/serde/StringSerde.java
ksml-data/src/main/java/io/axual/ksml/data/util/ConvertUtil.java
ksml/src/main/java/io/axual/ksml/operation/ConvertKeyOperation.java
ksml/src/main/java/io/axual/ksml/operation/ConvertKeyValueOperation.java
ksml/src/main/java/io/axual/ksml/operation/ConvertValueOperation.java

* Updates example 7 to convert to specific XML schema
* Fixes KeyError issue in example 13
* Update Protobuf schema since Apicurio only performs syntactical checks, not semantical (canonical)
* Makes expected type conversion explicit where possible for JSON, XML and StringSerde
* Don't pretty print XML output to Kafka (removes whitespaces in messages)
* Corrects some misplaced comment lines

Some small improvements to data conversion and corresponding examples

---

ksml/src/test/java/io/axual/ksml/BasicStreamRunTest.java

Fixes #248 (but may need further discussion and code change, see below). 
The Docker build on Intel Mac fails due to a failing test (`BasicStreamRunTest`). 
The cause of the error is in line 71 and following where a schema directory is set up. The schemas were moved to a separate directory `schemas` in an earlier PR but this class was overlooked  and still referred to `pipelines`.
The build works on other systems, this is most probably because of timing. `ExecutionContext` is a singleton instance which holds an instance of `SchemaLibrary`, since there are multiple tests that refer the `sensorData` schema, if a test runs earlier which loads the schema from the correct location, this test will work. If it is run first, it will fail.
For production runs the ExecutionContext is set up only …

Fix Docker build for Intel mac

---

ksml-runner/pom.xml
pom.xml

Added an invocation of the Maven exec plugin to call KSMLRunner to re-generate `docs/ksml-language-spec.json`.
The call is conditional, to regenerate the schema add a property to the Maven invocation:
```
mvn clean test -Dregenerate-schema
```
The schema location is configurable through a property in the root pom.

Regenerate ksml-language-spec.json from Maven (on demand)

---

.github/workflows/build-release-docs.yml

Added --allow-empty flag to all three mike commands in the workflow. This allows mike to create commits even when there are no changes to the documentation, which is useful for re-running deployments or when only metadata needs updating.

Mike `--allow-empty` flag
